/**
 * 5.0 stainID migration, part 2 — generate the data-dependent SQL.
 *
 * Reads every preset row (dyes, previous_values) from D1, rewrites legacy
 * itemIDs to stainIDs using the canonical map from core's dyes.json,
 * recomputes dye_signature (JSON.stringify of the sorted array — signatures
 * change, and duplicate detection breaks across eras otherwise), migrates the
 * previous_values JSON (it carries a dyes array; moderation revert would
 * otherwise restore legacy IDs into a stain-keyed system), and emits one
 * UPDATE per changed row.
 *
 * Usage (from apps/presets-api):
 *   npx wrangler d1 execute xivdyetools-presets --remote \
 *     --command "SELECT id, dyes, previous_values FROM presets" --json > /tmp/presets-rows.json
 *   npx tsx scripts/migrate-dyes-to-stainids.ts /tmp/presets-rows.json > migrations/generated-stainid-updates.sql
 *   # review, then apply in the same window as the 5.0 deploy:
 *   npx wrangler d1 execute xivdyetools-presets --remote --file migrations/0007_drop_community_category.sql
 *   npx wrangler d1 execute xivdyetools-presets --remote --file migrations/generated-stainid-updates.sql
 *
 * The ID spaces are disjoint (stainIDs 1-254, legacy itemIDs >= 5729), so the
 * script is idempotent: already-migrated rows produce no UPDATE.
 *
 * The output deliberately carries NO `BEGIN TRANSACTION` / `COMMIT`: D1 rejects
 * explicit transaction statements ("To execute a transaction, please use the
 * state.storage.transaction() … APIs instead of the SQL BEGIN TRANSACTION or
 * SAVEPOINT statements") and the whole `--file` batch fails before touching
 * data. `wrangler d1 execute --file` already runs the statements as one atomic
 * batch, so nothing is lost. Learned on the 2026-08-28 production run.
 */

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const DYES_PATH = resolve(here, '../../../packages/core/src/data/dyes.json');

interface DyeEntry {
  stainID: number;
  legacyItemID: number | null;
}

const dyes: DyeEntry[] = JSON.parse(readFileSync(DYES_PATH, 'utf8'));
const legacyToStain = new Map<number, number>();
for (const dye of dyes) {
  if (dye.legacyItemID !== null) legacyToStain.set(dye.legacyItemID, dye.stainID);
}

function mapDyes(ids: number[], rowId: string, field: string): { mapped: number[]; changed: boolean } {
  let changed = false;
  const mapped = ids.map((id) => {
    if (id >= 1 && id <= 254) return id; // already a stainID
    const stain = legacyToStain.get(id);
    if (stain === undefined) {
      throw new Error(`Row ${rowId} ${field}: id ${id} is neither a stainID nor a known legacy itemID`);
    }
    changed = true;
    return stain;
  });
  return { mapped, changed };
}

/** Matches preset-service generateDyeSignature: JSON string of sorted array. */
function signature(ids: number[]): string {
  return JSON.stringify([...ids].sort((a, b) => a - b));
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: tsx scripts/migrate-dyes-to-stainids.ts <wrangler-d1-json-output>');
  process.exit(1);
}

const raw = JSON.parse(readFileSync(inputPath, 'utf8'));
// wrangler --json emits [{ results: [...] , success, meta }]
const rows: Array<{ id: string; dyes: string; previous_values: string | null }> = Array.isArray(raw)
  ? (raw[0]?.results ?? [])
  : (raw.results ?? []);

console.log('-- Generated by migrate-dyes-to-stainids.ts — review before applying.');
console.log('-- dyes rewrite + dye_signature recompute + previous_values, one UPDATE per row.');
console.log('-- No BEGIN/COMMIT on purpose: D1 rejects explicit transactions; a `d1 execute');
console.log('-- --file` batch is already atomic.');

let updates = 0;
for (const row of rows) {
  const dyeIds: number[] = JSON.parse(row.dyes);
  const { mapped, changed } = mapDyes(dyeIds, row.id, 'dyes');

  let prevSql = '';
  let prevChanged = false;
  if (row.previous_values) {
    const prev = JSON.parse(row.previous_values) as { dyes?: number[] } & Record<string, unknown>;
    if (Array.isArray(prev.dyes)) {
      const prevMapped = mapDyes(prev.dyes, row.id, 'previous_values.dyes');
      if (prevMapped.changed) {
        prev.dyes = prevMapped.mapped;
        prevSql = `, previous_values = ${sqlString(JSON.stringify(prev))}`;
        prevChanged = true;
      }
    }
  }

  if (!changed && !prevChanged) continue;
  updates++;
  console.log(
    `UPDATE presets SET dyes = ${sqlString(JSON.stringify(mapped))}, ` +
      `dye_signature = ${sqlString(signature(mapped))}${prevSql} ` +
      `WHERE id = ${sqlString(row.id)};`
  );
}

console.error(`Rows scanned: ${rows.length}, updates emitted: ${updates}`);
