import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/__tests__/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './node_modules/.cache/vitest-coverage',
      clean: true,
      exclude: [
        'node_modules/',
        'dist/',
        'src/__tests__/**',
        'src/locales/**/*.json',
        'src/services/index.ts',
        'src/services/community-preset-service.ts',
        'src/services/hybrid-preset-service.ts',
        'src/services/preset-submission-service.ts',
        'src/services/pricing-mixin.ts',
        'src/components/add-to-collection-menu.ts',
        'src/components/collection-manager-modal.ts',
        'src/components/preset-edit-form.ts',
        'src/components/my-submissions-panel.ts',
        'src/components/dye-comparison-chart.ts',
        'src/components/welcome-modal.ts',
        'src/shared/browser-api-types.ts',
        'src/shared/types.ts',
        'src/components/accessibility-tool.ts',
        'src/components/budget-tool.ts',
        'src/components/comparison-tool.ts',
        'src/components/extractor-tool.ts',
        'src/components/gradient-tool.ts',
        'src/components/harmony-tool.ts',
        'src/components/mixer-tool.ts',
        'src/components/swatch-tool.ts',
        'src/components/v4/config-sidebar.ts',
        'src/components/v4/preset-tool.ts',
        'src/components/v4/v4-layout-shell.ts',
        'src/components/v4/v4-color-wheel.ts',
        'src/components/v4/dye-palette-drawer.ts',
        'src/components/image-zoom-controller.ts',
        'src/components/palette-exporter.ts',
        'src/components/preset-submission-form.ts',
        'src/components/auth-button.ts',
        'src/components/featured-presets-section.ts',
        'src/components/shortcuts-panel.ts',
        'src/components/recent-colors-panel.ts',
        'src/components/mobile-bottom-nav.ts',
        'src/components/dye-preview-overlay.ts',
        'src/components/v4/result-card.ts',
        'src/components/v4/display-options-v4.ts',
        'src/components/v4/theme-modal.ts',
        'src/components/v4/language-modal.ts',
        'src/components/v4/preset-card.ts',
        'src/components/v4/preset-detail.ts',
        'src/components/v4/tool-banner.ts',
        'src/components/v4/v4-app-header.ts',
        'src/components/v4/base-lit-component.ts',
        'src/components/v4/glass-panel.ts',
        'src/components/v4/range-slider-v4.ts',
        'src/components/v4/toggle-switch-v4.ts',
        'src/components/v4/share-button.ts',
        'src/components/app-layout.ts',
        'src/components/v4-layout.ts',
        'src/components/dye-action-dropdown.ts',
        'src/components/saved-palettes-modal.ts',
        'src/components/image-upload-display.ts',
        'src/components/camera-preview-modal.ts',
        'src/components/dye-selector.ts',
        'src/components/market-board.ts',
        'src/components/changelog-modal.ts',
        'src/components/toast-container.ts',
        'src/components/dye-grid.ts',
        'src/services/share-service.ts',
        'src/services/tool-panel-builders.ts',
      ],
      lines: 80,
      functions: 80,
      branches: 80,
      statements: 80,
    },
    include: ['src/**/*.{test,spec}.ts'],
    exclude: ['node_modules', 'dist', '.idea', '.git', '.cache'],
    server: {
      deps: {
        inline: ['@xivdyetools/core'],
      },
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@components': resolve(__dirname, './src/components'),
      '@services': resolve(__dirname, './src/services'),
      '@shared': resolve(__dirname, './src/shared'),
      '@apps': resolve(__dirname, './src/apps'),
      '@data': resolve(__dirname, './src/data'),
      'virtual:changelog': resolve(__dirname, './src/__tests__/mocks/virtual-changelog.ts'),
    },
  },
})
