/**
 * Vite plugin to make CSS load asynchronously to prevent render blocking
 */
import type { Plugin } from 'vite'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { createHash } from 'crypto'

/**
 * The loader's file name carries a content hash for the same reason every
 * other file under /assets/ does: `_headers` marks `/assets/*` as
 * `immutable` for a year. An un-hashed `load-css-async.js` stayed cached at
 * the edge and in browsers across deploys — production served a v4-era copy
 * (old CSS hash + a Google Fonts stylesheet the CSP then blocked) for weeks
 * after the 5.0 release, found 2026-08-29. A new stylesheet list is a new
 * file name, so an old cache entry can never be picked up by new HTML.
 */
export function asyncCssLoaderName(scriptContent: string): string {
  const hash = createHash('sha256').update(scriptContent).digest('hex').slice(0, 8)
  return `load-css-async-${hash}.js`
}

export function asyncCss(): Plugin {
  return {
    name: 'async-css',
    apply: 'build',
    writeBundle(options, _bundle) {
      // Find the HTML file in the bundle
      const htmlFile = resolve(options.dir || 'dist', 'index.html')
      
      try {
        let html = readFileSync(htmlFile, 'utf-8')
        
        // Collect all CSS files to load asynchronously
        const cssFiles: string[] = []
        
        // Find all CSS links
        html = html.replace(
          /<link\s+rel="stylesheet"[^>]*href="([^"]+\.css)"[^>]*>/g,
          (_match, href) => {
            cssFiles.push(href)
            // Remove the blocking CSS link, we'll load it async
            return ''
          }
        )
        
        // NOTE: this used to also hoist a `fonts.googleapis.com` stylesheet out
        // of the HTML. REFACTOR-002 self-hosted the typefaces, so no such link
        // can appear any more and the branch was removed rather than left as a
        // path that silently never runs.

        // Add async loading script before closing head tag
        if (cssFiles.length > 0) {
          // Create external script file for async CSS loading
          const scriptContent = `/**
 * Asynchronously load CSS to prevent render blocking
 * Generated by vite-plugin-async-css
 */
(function() {
  const stylesheets = ${JSON.stringify(cssFiles, null, 2)};
  stylesheets.forEach(function(href) {
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = href;
    link.media = 'all';
    document.head.appendChild(link);
  });
})();`
          
          const scriptName = asyncCssLoaderName(scriptContent)
          const scriptPath = resolve(options.dir || 'dist', 'assets', scriptName)
          const scriptUrl = `/assets/${scriptName}`
          
          // Write the script file
          const scriptDir = dirname(scriptPath)
          if (!existsSync(scriptDir)) {
            mkdirSync(scriptDir, { recursive: true })
          }
          writeFileSync(scriptPath, scriptContent, 'utf-8')
          
          // Add script reference to HTML
          const asyncScript = `
    <!-- Async CSS loading to prevent render blocking -->
    <script src="${scriptUrl}" defer></script>
    <noscript>
      ${cssFiles.map(href => `<link rel="stylesheet" href="${href}">`).join('\n      ')}
    </noscript>`
          
          // Insert before closing </head> tag
          html = html.replace('</head>', asyncScript + '\n  </head>')
        }
        
        writeFileSync(htmlFile, html, 'utf-8')
      } catch (error) {
        console.warn('Failed to process HTML for async CSS:', error)
      }
    },
  }
}

