/**
 * Vite plugin to make CSS load asynchronously to prevent render blocking
 */
import type { Plugin } from 'vite'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'

export function asyncCss(): Plugin {
  return {
    name: 'async-css',
    apply: 'build',
    writeBundle(options, bundle) {
      // Find the HTML file in the bundle
      const htmlFile = resolve(options.dir || 'dist', 'index.html')
      
      try {
        let html = readFileSync(htmlFile, 'utf-8')
        
        // Collect all CSS files to load asynchronously
        const cssFiles: string[] = []
        
        // Find all CSS links
        html = html.replace(
          /<link\s+rel="stylesheet"[^>]*href="([^"]+\.css)"[^>]*>/g,
          (match, href) => {
            cssFiles.push(href)
            // Remove the blocking CSS link, we'll load it async
            return ''
          }
        )
        
        // Also handle Google Fonts if present
        const fontUrls: string[] = []
        html = html.replace(
          /<link\s+href="(https:\/\/fonts\.googleapis\.com[^"]*)"\s+rel="stylesheet"[^>]*>/g,
          (match, href) => {
            fontUrls.push(href)
            return ''
          }
        )
        
        // Add async loading script before closing head tag
        if (cssFiles.length > 0 || fontUrls.length > 0) {
          // Create external script file for async CSS loading
          const scriptContent = `/**
 * Asynchronously load CSS to prevent render blocking
 * Generated by vite-plugin-async-css
 */
(function() {
  const stylesheets = ${JSON.stringify([...cssFiles, ...fontUrls], null, 2)};
  stylesheets.forEach(function(href) {
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = href;
    link.media = 'all';
    document.head.appendChild(link);
  });
})();`
          
          const scriptPath = resolve(options.dir || 'dist', 'assets', 'load-css-async.js')
          const scriptUrl = '/assets/load-css-async.js'
          
          // Write the script file
          const scriptDir = dirname(scriptPath)
          if (!existsSync(scriptDir)) {
            mkdirSync(scriptDir, { recursive: true })
          }
          writeFileSync(scriptPath, scriptContent, 'utf-8')
          
          // Add script reference to HTML
          const asyncScript = `
    <!-- Async CSS loading to prevent render blocking -->
    <script src="${scriptUrl}" defer></script>
    <noscript>
      ${cssFiles.map(href => `<link rel="stylesheet" href="${href}">`).join('\n      ')}
      ${fontUrls.map(href => `<link rel="stylesheet" href="${href}">`).join('\n      ')}
    </noscript>`
          
          // Insert before closing </head> tag
          html = html.replace('</head>', asyncScript + '\n  </head>')
        }
        
        writeFileSync(htmlFile, html, 'utf-8')
      } catch (error) {
        console.warn('Failed to process HTML for async CSS:', error)
      }
    },
  }
}

