/**
 * v5 KV data migration — clean up the deleted v4 commands' stored data.
 *
 * /match, /match_image, /favorites, /collection and /language were deleted in
 * v5 (design register decision). Their KV data migrates as follows:
 * - language: already migrated — the preferences service folds legacy
 *   `i18n:user:*` keys into `prefs:v1:*` on first read, so those keys are
 *   safe to delete once prefs have been touched (they also expire naturally).
 * - favorites/collections (`xivdye:favorites:v1:*`, `xivdye:collections:v1:*`):
 *   no v5 bot feature replaces them (saved things live in the web app's
 *   CollectionService); the keys are orphaned and get deleted.
 *
 * ⚠️ DEAD-010 (2026-08-18 audit): this script has NO step for the legacy
 * `budget:world:v1:*` world/datacenter preference. `preferences.ts`'s
 * `migrateLegacyPreferences` (see LEGACY_WORLD_PREFIX) still reads that
 * prefix on first access and folds it into `prefs:v1:*`, the same way it
 * does for `i18n:user:*` above — so the read-side migration code can never
 * be retired until those keys are swept too. Deliberately not added here:
 * whether to delete `budget:world:v1:*` now is a product decision, not a
 * dead-code cleanup.
 *
 * This script LISTS the keys and emits `wrangler kv key delete` commands —
 * it never deletes anything itself. Review the output, then pipe it to a
 * shell in the same maintenance window as the v5 deploy.
 *
 * Usage (from apps/discord-worker):
 *   npx wrangler kv key list --binding KV --remote --prefix "xivdye:favorites:" > /tmp/kv-fav.json
 *   npx wrangler kv key list --binding KV --remote --prefix "xivdye:collections:" > /tmp/kv-col.json
 *   npx wrangler kv key list --binding KV --remote --prefix "i18n:user:" > /tmp/kv-i18n.json
 *   npx tsx scripts/cleanup-v4-kv.ts /tmp/kv-fav.json /tmp/kv-col.json /tmp/kv-i18n.json > /tmp/kv-cleanup.sh
 *   # review /tmp/kv-cleanup.sh, then run it
 */

import { readFileSync } from 'node:fs';

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('Usage: tsx scripts/cleanup-v4-kv.ts <wrangler-kv-list-json>...');
  process.exit(1);
}

const EXPECTED_PREFIXES = ['xivdye:favorites:', 'xivdye:collections:', 'i18n:user:'];

let total = 0;
console.log('#!/bin/sh');
console.log('# Generated by cleanup-v4-kv.ts — review before running.');
for (const file of files) {
  const keys: Array<{ name: string }> = JSON.parse(readFileSync(file, 'utf8'));
  for (const key of keys) {
    if (!EXPECTED_PREFIXES.some((p) => key.name.startsWith(p))) {
      console.error(`SKIPPED unexpected key (not a v4 prefix): ${key.name}`);
      continue;
    }
    total++;
    console.log(
      `npx wrangler kv key delete --binding KV --remote "${key.name.replace(/"/g, '\\"')}"`,
    );
  }
}
console.error(`Delete commands emitted: ${total}`);
