#!/usr/bin/env tsx
/**
 * Writes `src/data/oklch-hue-table.json` — the OKLCH-hue wheel's warp table.
 *
 *   pnpm --filter @xivdyetools/core run build:oklch-hue
 *
 * Deliberately NOT part of `build`: the JSON is committed, and a table that
 * regenerates on every build is a table nobody reviews. Re-run it only when
 * the derivation itself changes, and put the before/after digests of
 * `HarmonySelector.golden.test.ts` in the commit body.
 */

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deriveOklchHueTable } from './lib/oklch-hue-table.js';

const table = deriveOklchHueTable();
const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/oklch-hue-table.json');

writeFileSync(
  outPath,
  JSON.stringify(
    {
      $comment:
        'Generated by scripts/build-oklch-hue-table.ts (pnpm run build:oklch-hue) — [oklabHue, hsvHue] pairs for the fully saturated sRGB hue circle. Do not edit by hand.',
      table,
    },
    null,
    2
  ) + '\n',
  'utf-8'
);

console.log(`Wrote ${table.length} pairs to ${outPath}`);
