/**
 * Font Loading Service
 *
 * Provides font file buffers for SVG-to-PNG rendering with resvg-wasm.
 * Fonts are bundled directly into the Worker at build time by wrangler.
 *
 * Brand fonts:
 * - Space Grotesk: Headers (variable weight 300-700)
 * - Onest: Body text, labels (variable weight 100-900)
 * - Fragment Mono: Hex codes and numeric columns (5.0 — replaced Habibi,
 *   which was a proportional serif and never aligned numbers)
 *
 * CJK subset fonts (dye names in ja/ko/zh):
 * - Noto Sans JP: Japanese kana + kanji (Japanese letterforms — before the
 *   JP subset, ja rendered out of the SC subset in Chinese letterforms)
 * - Noto Sans SC: Chinese ideographs + fallback for everything CJK
 * - Noto Sans KR: Korean Hangul syllables
 * Generated by scripts/subset-cjk-fonts.py — re-run when new dyes are added.
 */

// Static font imports - wrangler bundles these as ArrayBuffer at build time.
//
// The brand faces ship as STATIC instances (Regular / SemiBold / Bold), never
// the variable files: resvg's font database cannot move a variable axis, so a
// variable file exposes only its default instance and every `font-weight` the
// band cards asked for rendered at that one weight (Space Grotesk's default is
// Light 300). Regenerate with
// apps/discord-worker/scripts/instance-latin-fonts.py --app og-worker;
// font-faces.test.ts renders 400 / 600 / 700 and fails if any two match.
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskRegular from '../fonts/SpaceGrotesk-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskSemiBold from '../fonts/SpaceGrotesk-SemiBold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskBold from '../fonts/SpaceGrotesk-Bold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestRegular from '../fonts/Onest-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestSemiBold from '../fonts/Onest-SemiBold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestBold from '../fonts/Onest-Bold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import fragmentMonoData from '../fonts/FragmentMono-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansJPData from '../fonts/NotoSansJP-Subset.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansSCData from '../fonts/NotoSansSC-Subset.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansKRData from '../fonts/NotoSansKR-Subset.ttf';

// Cache font buffers to avoid repeated conversions
let fontBuffersCache: Uint8Array[] | null = null;

/**
 * Returns font file data as Uint8Array buffers for resvg-wasm.
 * Buffers are cached after first call.
 *
 * Usage with resvg:
 * ```typescript
 * const resvg = new Resvg(svgString, {
 *   font: {
 *     fontBuffers: getFontBuffers(),
 *     defaultFontFamily: 'Onest',
 *   },
 * });
 * ```
 */
export function getFontBuffers(): Uint8Array[] {
  if (fontBuffersCache) {
    return fontBuffersCache;
  }

  fontBuffersCache = [
    new Uint8Array(spaceGroteskRegular),
    new Uint8Array(spaceGroteskSemiBold),
    new Uint8Array(spaceGroteskBold),
    new Uint8Array(onestRegular),
    new Uint8Array(onestSemiBold),
    new Uint8Array(onestBold),
    new Uint8Array(fragmentMonoData),
    new Uint8Array(notoSansJPData),
    new Uint8Array(notoSansSCData),
    new Uint8Array(notoSansKRData),
  ];

  return fontBuffersCache;
}

