/**
 * Font Loading Service
 *
 * Provides font file buffers for SVG-to-PNG rendering with resvg-wasm.
 * Fonts are bundled directly into the Worker at build time by wrangler.
 *
 * Brand fonts:
 * - Space Grotesk: Headers (variable weight 300-700)
 * - Onest: Body text, labels (variable weight 100-900)
 * - Fragment Mono: Hex codes and numeric columns (5.0 — replaced Habibi,
 *   which was a proportional serif and never aligned numbers)
 *
 * CJK subset fonts (dye names in ja/ko/zh):
 * - Noto Sans JP: Japanese kana + kanji (Japanese letterforms — before the
 *   JP subset, ja rendered out of the SC subset in Chinese letterforms)
 * - Noto Sans SC: Chinese ideographs + fallback for everything CJK
 * - Noto Sans KR: Korean Hangul syllables
 * Generated by scripts/subset-cjk-fonts.py — re-run when new dyes are added.
 */

// Static font imports - wrangler bundles these as ArrayBuffer at build time
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskData from '../fonts/SpaceGrotesk-VariableFont_wght.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestData from '../fonts/Onest-VariableFont_wght.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import fragmentMonoData from '../fonts/FragmentMono-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansJPData from '../fonts/NotoSansJP-Subset.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansSCData from '../fonts/NotoSansSC-Subset.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansKRData from '../fonts/NotoSansKR-Subset.ttf';

// Cache font buffers to avoid repeated conversions
let fontBuffersCache: Uint8Array[] | null = null;

/**
 * Returns font file data as Uint8Array buffers for resvg-wasm.
 * Buffers are cached after first call.
 *
 * Usage with resvg:
 * ```typescript
 * const resvg = new Resvg(svgString, {
 *   font: {
 *     fontBuffers: getFontBuffers(),
 *     defaultFontFamily: 'Onest',
 *   },
 * });
 * ```
 */
export function getFontBuffers(): Uint8Array[] {
  if (fontBuffersCache) {
    return fontBuffersCache;
  }

  fontBuffersCache = [
    new Uint8Array(spaceGroteskData),
    new Uint8Array(onestData),
    new Uint8Array(fragmentMonoData),
    new Uint8Array(notoSansJPData),
    new Uint8Array(notoSansSCData),
    new Uint8Array(notoSansKRData),
  ];

  return fontBuffersCache;
}

/** CJK fallback stack for a locale — ja gets Japanese letterforms first. */
export function cjkStack(locale: string): string {
  return locale === 'ja'
    ? 'Noto Sans JP, Noto Sans SC, Noto Sans KR'
    : 'Noto Sans SC, Noto Sans KR';
}

/**
 * Font family names as they appear in the font metadata.
 * Use these names in SVG font-family attributes. For localized text, prefer
 * `cjkStack(locale)` composed with the base family so ja text takes the JP
 * subset before falling back to SC.
 */
export const FONT_FAMILIES = {
  /** Space Grotesk - for headers and titles */
  header: 'Space Grotesk',
  /** Onest - for body text and labels */
  body: 'Onest',
  /** Fragment Mono - for hex codes and numeric columns (no CJK glyphs) */
  mono: 'Fragment Mono',
  /** Onest with CJK fallback - for localized dye names.
   *  NOTE: JP-first belongs only to ja — compose with cjkStack(locale) so zh
   *  never picks up Japanese letterforms for shared ideographs. */
  bodyCjk: 'Onest, Noto Sans SC, Noto Sans KR',
  /** Space Grotesk with CJK fallback - for localized headers */
  headerCjk: 'Space Grotesk, Noto Sans SC, Noto Sans KR',
} as const;
