/**
 * The shader half of `human.cmp` — the color the game renders each palette
 * entry from, which is what a `.chara` extended float stores (squared).
 *
 * The game keeps every palette twice: the interface half is the creator's
 * swatch (`CharacterColorService`, what the tools show and match dyes
 * against) and the shader half is what reaches the model. Judging a float
 * needs the shader half: across the 2026-09-28 corpus every unedited float
 * equals it exactly — hair 982 of 982, skin 980 of 982, limbal 797 of 798 —
 * where the interface half never matches skin at all. Only the `.chara`
 * resolver reads this module, so nothing else bundles the clan tables.
 *
 * Generated by `scripts/build-character-colors.ts` from the game file.
 */

import type { Gender, SubRace } from '@xivdyetools/types';

/** Shader palettes a `.chara` float can be judged against. */
export type CharaShaderPalette = 'eyes' | 'highlights' | 'features' | 'lipsDark' | 'skin' | 'hair';

type ClanTable = Record<string, Record<string, string[]>>;
interface RaceShaderData {
  skin: ClanTable;
  hair: ClanTable;
}
type SharedShaderData = Record<string, string[]>;

// Both tables load on first use: the web app's core-runtime chunk has no room for them, and
// only a resolved .chara file ever needs them
let sharedShaderLoading: Promise<SharedShaderData> | null = null;
let raceShaderLoading: Promise<RaceShaderData> | null = null;

function loadSharedShaderData(): Promise<SharedShaderData> {
  sharedShaderLoading ??= import('../../data/character_colors/shader/shared.json').then(
    (module) => (module.default ?? module) as SharedShaderData,
  );
  return sharedShaderLoading;
}

function loadRaceShaderData(): Promise<RaceShaderData> {
  raceShaderLoading ??= import('../../data/character_colors/shader/race_specific.json').then(
    (module) => (module.default ?? module) as RaceShaderData,
  );
  return raceShaderLoading;
}

/**
 * The stored color for a palette entry, or null when the palette has no such
 * entry (or the clan table needs a tribe and gender the file does not name).
 */
export async function charaShaderHex(
  palette: CharaShaderPalette,
  index: number,
  subrace: SubRace | null,
  gender: Gender | null,
): Promise<string | null> {
  if (palette === 'skin' || palette === 'hair') {
    if (!subrace || !gender) return null;
    const table = (await loadRaceShaderData())[palette];
    return table[subrace]?.[gender]?.[index] ?? null;
  }
  return (await loadSharedShaderData())[palette][index] ?? null;
}
