/**
 * Emoji Service
 *
 * Provides Discord emoji strings for FFXIV dyes.
 * Emojis are uploaded as Application Emojis and referenced by ID.
 */

// Import emoji mapping generated by upload-emojis.ts script
import emojiMapping from '../data/emoji-mapping.json';

// Type the mapping as Record<string, string> (itemID -> emoji string)
const mapping = emojiMapping as Record<string, string>;

/**
 * Get Discord emoji string for a dye by its item ID
 * @returns Emoji string like "<:dalamud_red:1234567890>" or undefined if not found
 */
export function getDyeEmoji(itemId: number): string | undefined {
  return mapping[String(itemId)];
}


