/**
 * Font Loading Service
 *
 * Provides font file buffers for SVG-to-PNG rendering with resvg-wasm.
 * Fonts are bundled directly into the Worker at build time by wrangler.
 *
 * Brand fonts:
 * - Space Grotesk: Headers (variable weight 300-700)
 * - Onest: Body text, labels (variable weight 100-900)
 * - Fragment Mono: Hex codes and numeric columns (5.0 — replaced Habibi,
 *   which was a proportional serif and never aligned numbers)
 *
 * CJK fonts (for Japanese/Korean/Chinese support) — three subsets, all
 * generated by scripts/subset-cjk-fonts.py from the codepoints present in the
 * core + bot-logic/i18n locale JSON files and api-worker's ko / zh item-name
 * tables (FONT-001 — re-run it after any locale edit or item-table rebuild):
 * - Noto Sans SC: terminal CJK fallback for every language (Chinese ideographs,
 *   incl. every zh item name, plus the Japanese kanji/kana) — ~839 KiB (858,784 B)
 * - Noto Sans JP: Japanese letterforms, ahead of SC for ja only (5.0)
 *   — ~330 KiB (337,708 B)
 * - Noto Sans KR: Hangul syllables (incl. every ko item name) + ASCII
 *   — ~201 KiB (206,300 B)
 *
 * The three subsets total ~1.37 MiB raw / ~0.8 MiB gzipped; the binding limit
 * is Cloudflare's 3 MiB *gzipped* Worker size (`pnpm run check-bundle-size`
 * reports the real figure).
 */

// Static font imports - wrangler bundles these as ArrayBuffer at build time.
//
// The brand faces ship as STATIC instances (Regular / SemiBold / Bold), never
// the variable files: resvg's font database cannot move a variable axis, so a
// variable file exposes only its default instance and every `font-weight` the
// cards asked for rendered at that one weight (Space Grotesk's default is
// Light 300 — every title shipped thin until 2026-08-29). Regenerate with
// scripts/instance-latin-fonts.py (sources in scripts/font-sources/);
// font-faces.test.ts renders 400 / 600 / 700 and fails if any two match.
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskRegular from '../fonts/SpaceGrotesk-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskSemiBold from '../fonts/SpaceGrotesk-SemiBold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskBold from '../fonts/SpaceGrotesk-Bold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestRegular from '../fonts/Onest-Regular.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestSemiBold from '../fonts/Onest-SemiBold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestBold from '../fonts/Onest-Bold.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import fragmentMonoData from '../fonts/FragmentMono-Regular.ttf';

// CJK font imports - subsetted via apps/discord-worker/scripts/subset-cjk-fonts.py
// Noto Sans SC: Chinese ideographs + Japanese kanji/kana (~839 KiB)
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansCjkData from '../fonts/NotoSansSC-Subset.ttf';
// Noto Sans KR: Korean Hangul syllables
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansKrData from '../fonts/NotoSansKR-Subset.ttf';
// Noto Sans JP: Japanese kana + kanji in Japanese letterforms (5.0 — before
// this subset, ja rendered out of the SC subset in Chinese letterforms)
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansJpData from '../fonts/NotoSansJP-Subset.ttf';

// Cache font buffers to avoid repeated conversions
let fontBuffersCache: Uint8Array[] | null = null;

/**
 * Returns font file data as Uint8Array buffers for resvg-wasm.
 * Buffers are cached after first call.
 *
 * Usage with resvg:
 * ```typescript
 * const resvg = new Resvg(svgString, {
 *   font: {
 *     fontBuffers: getFontBuffers(),
 *     defaultFontFamily: 'Onest',
 *   },
 * });
 * ```
 */
export function getFontBuffers(): Uint8Array[] {
  if (fontBuffersCache) {
    return fontBuffersCache;
  }

  const buffers: Uint8Array[] = [
    new Uint8Array(spaceGroteskRegular as ArrayBuffer),
    new Uint8Array(spaceGroteskSemiBold as ArrayBuffer),
    new Uint8Array(spaceGroteskBold as ArrayBuffer),
    new Uint8Array(onestRegular as ArrayBuffer),
    new Uint8Array(onestSemiBold as ArrayBuffer),
    new Uint8Array(onestBold as ArrayBuffer),
    new Uint8Array(fragmentMonoData as ArrayBuffer),
  ];

  // Add CJK fonts if available
  if (notoSansCjkData) {
    buffers.push(new Uint8Array(notoSansCjkData as ArrayBuffer));
  }
  if (notoSansKrData) {
    buffers.push(new Uint8Array(notoSansKrData as ArrayBuffer));
  }
  if (notoSansJpData) {
    buffers.push(new Uint8Array(notoSansJpData as ArrayBuffer));
  }

  fontBuffersCache = buffers;
  return fontBuffersCache;
}
