/**
 * Font Loading Service
 *
 * Provides font file buffers for SVG-to-PNG rendering with resvg-wasm.
 * Fonts are bundled directly into the Worker at build time by wrangler.
 *
 * Brand fonts:
 * - Space Grotesk: Headers (variable weight 300-700)
 * - Onest: Body text, labels (variable weight 100-900)
 * - Fragment Mono: Hex codes and numeric columns (5.0 — replaced Habibi,
 *   which was a proportional serif and never aligned numbers)
 *
 * CJK fonts (for Japanese/Korean/Chinese support) — three subsets, all
 * generated by scripts/subset-cjk-fonts.py from the codepoints present in the
 * core + bot-logic/i18n locale JSON files (re-run it after any locale edit):
 * - Noto Sans SC: terminal CJK fallback for every language (Chinese ideographs
 *   plus the Japanese kanji/kana) — ~844 KiB (863,940 B)
 * - Noto Sans JP: Japanese letterforms, ahead of SC for ja only (5.0)
 *   — ~571 KiB (584,804 B)
 * - Noto Sans KR: Hangul syllables + ASCII — ~233 KiB (238,780 B)
 *
 * The three subsets total ~1.6 MiB raw / ~1.0 MiB gzipped; the binding limit
 * is Cloudflare's 3 MiB *gzipped* Worker size (`wrangler deploy --dry-run`
 * reports the real figure).
 */

// Static font imports - wrangler bundles these as ArrayBuffer at build time
// @ts-expect-error - Binary imports are handled by wrangler bundler
import spaceGroteskData from '../fonts/SpaceGrotesk-VariableFont_wght.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import onestData from '../fonts/Onest-VariableFont_wght.ttf';
// @ts-expect-error - Binary imports are handled by wrangler bundler
import fragmentMonoData from '../fonts/FragmentMono-Regular.ttf';

// CJK font imports - subsetted via apps/discord-worker/scripts/subset-cjk-fonts.py
// Noto Sans SC: Chinese ideographs + Japanese kanji/kana (~844 KiB)
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansCjkData from '../fonts/NotoSansSC-Subset.ttf';
// Noto Sans KR: Korean Hangul syllables
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansKrData from '../fonts/NotoSansKR-Subset.ttf';
// Noto Sans JP: Japanese kana + kanji in Japanese letterforms (5.0 — before
// this subset, ja rendered out of the SC subset in Chinese letterforms)
// @ts-expect-error - Binary imports are handled by wrangler bundler
import notoSansJpData from '../fonts/NotoSansJP-Subset.ttf';

// Cache font buffers to avoid repeated conversions
let fontBuffersCache: Uint8Array[] | null = null;

/**
 * Returns font file data as Uint8Array buffers for resvg-wasm.
 * Buffers are cached after first call.
 *
 * Usage with resvg:
 * ```typescript
 * const resvg = new Resvg(svgString, {
 *   font: {
 *     fontBuffers: getFontBuffers(),
 *     defaultFontFamily: 'Onest',
 *   },
 * });
 * ```
 */
export function getFontBuffers(): Uint8Array[] {
  if (fontBuffersCache) {
    return fontBuffersCache;
  }

  const buffers: Uint8Array[] = [
    new Uint8Array(spaceGroteskData as ArrayBuffer),
    new Uint8Array(onestData as ArrayBuffer),
    new Uint8Array(fragmentMonoData as ArrayBuffer),
  ];

  // Add CJK fonts if available
  if (notoSansCjkData) {
    buffers.push(new Uint8Array(notoSansCjkData as ArrayBuffer));
  }
  if (notoSansKrData) {
    buffers.push(new Uint8Array(notoSansKrData as ArrayBuffer));
  }
  if (notoSansJpData) {
    buffers.push(new Uint8Array(notoSansJpData as ArrayBuffer));
  }

  fontBuffersCache = buffers;
  return fontBuffersCache;
}
